title: Florencia Mangini # your name (or website title) here
description: > # Data Analyst | Data Scientist (remove <br> elements if you don't need line breaks)
  <br><br>
  A data-driven professional with a MS in Data Science and extensive experience in project management (PMP / ACP-PMI/Scrum Master) and data analysis. 
  +10 Years of experience working in Technology.
  <br><br>
  <a href="https://www.linkedin.com/in/flomangini/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.novypro.com/profile_projects/florencia">View My Dashboard Portofolio</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-RYR04MDZ0Z # your Google Analytics tracking ID here
